In [2]:
import os
from google.colab import userdata
import kagglehub
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
data_path = "/content/drive/MyDrive/ADS2002"

train_labels = pd.read_csv(f"{data_path}/train_labels.csv")
test_labels = pd.read_csv(f"{data_path}/test_labels.csv")

!unzip -q "{data_path}/train.zip" -d /content/train_images
!unzip -q "{data_path}/test.zip" -d /content/test_images

Mounted at /content/drive

In [3]:
train_labels

,image_name,patient_id,sex,age_approx,anatom_site_general_challenge,diagnosis,benign_malignant,target
0,ISIC_0015719,IP_3075186,female,45.0,upper extremity,unknown,benign,0
1,ISIC_0074542,IP_4698288,male,25.0,lower extremity,unknown,benign,0
2,ISIC_0076545,IP_9802602,male,55.0,upper extremity,unknown,benign,0
3,ISIC_0082348,IP_7684360,male,55.0,torso,unknown,benign,0
4,ISIC_0085172,IP_1705144,female,50.0,lower extremity,unknown,benign,0
...,...,...,...,...,...,...,...,...
6859,ISIC_9988492,IP_8173459,female,50.0,torso,unknown,benign,0
6860,ISIC_9990676,IP_3686214,female,55.0,lower extremity,nevus,benign,0
6861,ISIC_9991394,IP_2321962,female,30.0,torso,unknown,benign,0
6862,ISIC_9991967,IP_2507276,male,70.0,lower extremity,nevus,benign,0
6863,ISIC_9997614,IP_1705144,female,50.0,upper extremity,nevus,benign,0

In [4]:
train_labels.describe()

        age_approx       target
count  6864.000000  6864.000000
mean     48.944493     0.018648
std      14.401600     0.135288
min      15.000000     0.000000
25%      40.000000     0.000000
50%      50.000000     0.000000
75%      60.000000     0.000000
max      90.000000     1.000000

In [5]:
train_labels.isna().sum()

image_name                         0
patient_id                         0
sex                                0
age_approx                         0
anatom_site_general_challenge    196
diagnosis                          0
benign_malignant                   0
target                             0
dtype: int64

In [15]:
print(f"Number of unique patients: {len(train_labels) - train_labels["patient_id"].duplicated().sum()}")

Number of unique patients: 422

In [6]:
test_labels

,image_name,patient_id,sex,age_approx,anatom_site_general_challenge,diagnosis,benign_malignant,target
0,ISIC_0088489,IP_9147454,female,55.0,torso,unknown,benign,0
1,ISIC_0096201,IP_9906695,female,45.0,torso,nevus,benign,0
2,ISIC_0097500,IP_9147454,female,55.0,upper extremity,unknown,benign,0
3,ISIC_0112444,IP_9147454,female,55.0,torso,unknown,benign,0
4,ISIC_0148465,IP_1517386,male,40.0,head/neck,unknown,benign,0
...,...,...,...,...,...,...,...,...
1983,ISIC_9981394,IP_8352243,female,40.0,upper extremity,unknown,benign,0
1984,ISIC_9998152,IP_4356379,female,40.0,lower extremity,unknown,benign,0
1985,ISIC_9998682,IP_2516168,male,60.0,head/neck,melanoma,malignant,1
1986,ISIC_9999127,IP_9583707,male,20.0,torso,unknown,benign,0
1987,ISIC_9999515,IP_2026598,male,20.0,lower extremity,unknown,benign,0

In [7]:
test_labels.describe()

        age_approx       target
count  1988.000000  1988.000000
mean     50.364688     0.015594
std      14.808977     0.123928
min      10.000000     0.000000
25%      40.000000     0.000000
50%      50.000000     0.000000
75%      60.000000     0.000000
max      90.000000     1.000000

In [10]:
test_labels.isna().sum()

image_name                        0
patient_id                        0
sex                               0
age_approx                        0
anatom_site_general_challenge    24
diagnosis                         0
benign_malignant                  0
target                            0
dtype: int64

In [16]:
print(f"Number of unique patients: {len(test_labels) - test_labels["patient_id"].duplicated().sum()}")

Number of unique patients: 106

In [8]:
train_patients = set(train_labels['patient_id'])
test_patients = set(test_labels['patient_id'])
overlap = train_patients & test_patients
print(len(overlap))

0